<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Get category IDs by name
        $categories = Category::pluck('id', 'name');

        $products = [
            // ── Dog Food (20) ──
            ['name' => 'AOZI Dog Dry Food (Adult) Gold Beef Flavor 1kg', 'category' => 'Dog Food', 'description' => 'Premium AOZI adult dog dry food with rich beef flavor. Gold variant packed with essential nutrients for adult dogs. 1kg pack.', 'price' => 178, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/102691_1_8c092e79-e483-4a07-b3d9-ff4a38274a6d.jpg?v=1702884391'],
            ['name' => 'AOZI Dog Dry Food (Puppy) Blue Lamb Organic Apple 1kg', 'category' => 'Dog Food', 'description' => 'AOZI puppy formula with lamb and organic apple. Blue variant specially formulated for growing puppies. 1kg pack.', 'price' => 210, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/102691_2_1600x1600.jpg?v=1702881060'],
            ['name' => 'AOZI Dog Wet Food in Can Chicken Yellow 430g', 'category' => 'Dog Food', 'description' => 'Delicious AOZI wet dog food with tender chicken chunks in savory gravy. Yellow variant. 430g can.', 'price' => 90, 'unit' => 'CAN', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/5546c6fc0d86176ee632ba602d8b3821_1600x1600.jpg?v=1776237657'],
            ['name' => 'AOZI Dog Wet Food in Can Lamb & Liver Dark Green 430g', 'category' => 'Dog Food', 'description' => 'AOZI premium wet food with lamb and liver combo for adult dogs. Rich in protein. 430g can.', 'price' => 95, 'unit' => 'CAN', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/5546c6fc0d86176ee632ba602d8b3821_1600x1600.jpg?v=1776237657'],
            ['name' => 'BEEFPRO Dog Dry Food (Adult) 1kg', 'category' => 'Dog Food', 'description' => 'BEEFPRO adult dog dry food with high-quality beef protein. Balanced nutrition for daily feeding. 1kg pack.', 'price' => 150, 'unit' => '1kilogram', 'image' => 'https://merpstore.com/cdn/shop/products/ph-11134201-7qul7-ley91p34oxla68_809ee474-76cd-44fc-b3f1-7023f7b30d20.jpg?v=1681794789'],
            ['name' => 'BEEFPRO Dog Dry Food (Puppy) 1kg', 'category' => 'Dog Food', 'description' => 'BEEFPRO puppy formula enriched with vitamins and minerals for healthy growth and development. 1kg pack.', 'price' => 180, 'unit' => '1kilogram', 'image' => 'https://merpstore.com/cdn/shop/products/ph-11134201-7qul7-ley91p34oxla68_809ee474-76cd-44fc-b3f1-7023f7b30d20.jpg?v=1681794789'],
            ['name' => 'CHAPPI Dog Dry Food (Adult) Chicken 1kg', 'category' => 'Dog Food', 'description' => 'CHAPPI adult dog food with real chicken flavor. Affordable daily nutrition for your furry friend. 1kg pack.', 'price' => 100, 'unit' => '1kilogram', 'image' => 'https://img.lazcdn.com/g/p/6b9eaa84afa41bc16101afca60bb279a.png_720x720q80.png_.webp'],
            ['name' => 'PEDIGREE Dog Dry Food (Adult) Beef and Vegetables 1kg', 'category' => 'Dog Food', 'description' => 'PEDIGREE complete nutrition with beef and vegetables. Supports strong bones, healthy skin and a shiny coat. 1kg pack.', 'price' => 160, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10187821_6a951197-ebbd-424a-a8bf-5187e053ebbe_800x800.jpg'],
            ['name' => 'PEDIGREE Dog Dry Food (Puppy) Chicken Egg Milk 1kg', 'category' => 'Dog Food', 'description' => 'PEDIGREE puppy food with chicken, egg and milk for growing puppies. DHA for brain development. 1kg pack.', 'price' => 180, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10266027_b5eb0036-3536-42fa-9472-f34685bac7ea_1600x1600.jpg?v=1778557308'],
            ['name' => 'PEDIGREE Dog Wet Food in Can Homestyle Beef 400g', 'category' => 'Dog Food', 'description' => 'PEDIGREE homestyle beef wet food in a 400g can. Meaty chunks in rich gravy dogs love.', 'price' => 122, 'unit' => 'CAN', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10164256PedigreeAdultBeefWetDogFood400g_3cans_A_800x800.png'],
            ['name' => 'PEDIGREE Dog Wet Food Pouch Chicken in Gravy 130g', 'category' => 'Dog Food', 'description' => 'PEDIGREE wet food pouch with chicken in savory gravy. Perfect topper or standalone meal. 130g pouch.', 'price' => 40, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10216184_913c6a2a-57d8-42af-b03e-d150a2fb5334_800x800.jpg'],
            ['name' => 'SPECIAL DOG Dry Food (Adult) Lamb and Rice 1kg', 'category' => 'Dog Food', 'description' => 'SPECIAL DOG adult formula with lamb and rice. Gentle on sensitive stomachs. 1kg pack.', 'price' => 145, 'unit' => '1kilogram', 'image' => 'https://www.petcultureph.com/cdn/shop/files/SpecialDogAdult.png?v=1695032197'],
            ['name' => 'SPECIAL DOG Dry Food (Puppy) Lamb and Rice 1kg', 'category' => 'Dog Food', 'description' => 'SPECIAL DOG puppy formula with lamb and rice for easy digestion and healthy growth. 1kg pack.', 'price' => 150, 'unit' => '1kilogram', 'image' => 'https://www.petcultureph.com/cdn/shop/files/SpecialDogAdult.png?v=1695032197'],
            ['name' => 'SPECIAL DOG Wet Food in Can Blue Lamb Turkey 400g', 'category' => 'Dog Food', 'description' => 'SPECIAL DOG wet food with lamb and turkey. Blue variant. Rich protein meal in a 400g can.', 'price' => 90, 'unit' => 'CAN', 'image' => 'https://www.petcultureph.com/cdn/shop/files/SpecialDogAdult.png?v=1695032197'],
            ['name' => 'TOPBREED Dog Meal (Adult) 1kg', 'category' => 'Dog Food', 'description' => 'TOPBREED affordable adult dog meal. Complete daily nutrition at a budget-friendly price. 1kg pack.', 'price' => 80, 'unit' => '1kilogram', 'image' => 'https://www.petcultureph.com/cdn/shop/files/Topbreedadult.png?v=1705563228'],
            ['name' => 'TOPBREED Dog Meal (Puppy) 1kg', 'category' => 'Dog Food', 'description' => 'TOPBREED puppy meal with essential nutrients for healthy puppy growth. Budget-friendly. 1kg pack.', 'price' => 96, 'unit' => '1kilogram', 'image' => 'https://www.petcultureph.com/cdn/shop/files/Topbreedadult.png?v=1705563228'],
            ['name' => 'VITALITY Dog Dry Food (Adult) Classic Lamb and Beef 1kg', 'category' => 'Dog Food', 'description' => 'VITALITY premium adult dog food with classic lamb and beef recipe. High-quality ingredients. 1kg pack.', 'price' => 196, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/10177665-Vitality-Classic-Lamb-and-Beef-Dry-Dog-Food-3kg-front_1600x1600.jpg?v=1645069573'],
            ['name' => 'HOLISTIC RECIPE Dog Dry Food (Adult) Lamb Rice Green Tea 1kg', 'category' => 'Dog Food', 'description' => 'HOLISTIC RECIPE with lamb meal, rice and green tea extract. Natural antioxidants for adult dogs. 1kg pack.', 'price' => 200, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/10164207_1_1600x1600.jpg?v=1626330053'],
            ['name' => 'DOGGO Dog Wet Food Pouch Juicy Beef with Sauce 75g', 'category' => 'Dog Food', 'description' => 'DOGGO wet food pouch with juicy beef in savory sauce. All life stages. Convenient 75g pouch.', 'price' => 40, 'unit' => 'POUCH', 'image' => 'https://www.petcultureph.com/cdn/shop/files/Doggo_Wet_Food_Delicious_Duck_150G.png?v=1742105978'],
            ['name' => 'WHOOPPY Dog Dry Food (Adult) Beef Flavour 1kg', 'category' => 'Dog Food', 'description' => 'WHOOPPY adult dog food with savory beef flavor. Affordable everyday nutrition. 1kg pack.', 'price' => 75, 'unit' => '1kilogram', 'image' => 'https://www.jetbest.com.ph/wp-content/uploads/2022/10/group_whooppy.png'],

            // ── Cat Food (15) ──
            ['name' => 'AOZI Cat Dry Food (Kitten) Yellow 1kg', 'category' => 'Cat Food', 'description' => 'AOZI premium kitten dry food. Yellow variant with balanced nutrition for growing kittens. 1kg pack.', 'price' => 210, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10276793-Aozi-Kitten-Dry-Cat-Food-2.5kg-FRONT_1600x1600.png?v=1708407571'],
            ['name' => 'MONELLO Cat Dry Food (Adult) Salmon and Chicken 1kg', 'category' => 'Cat Food', 'description' => 'MONELLO adult cat food with salmon and chicken. Premium recipe for healthy adult cats. 1kg pack.', 'price' => 180, 'unit' => '1kilogram', 'image' => 'https://www.momoypetsupplies.com/web/image/product.template/303/image_1920?unique=cbfd47f'],
            ['name' => 'MONELLO Hairball Green 1kg', 'category' => 'Cat Food', 'description' => 'MONELLO hairball control formula for cats. Green variant helps reduce hairball formation. 1kg pack.', 'price' => 200, 'unit' => '1kilogram', 'image' => 'https://www.momoypetsupplies.com/web/image/product.template/303/image_1920?unique=cbfd47f'],
            ['name' => 'SPECIAL CAT Dry Food (Adult) Urinary 1kg', 'category' => 'Cat Food', 'description' => 'SPECIAL CAT urinary health formula for adult cats. Supports urinary tract health. 1kg pack.', 'price' => 200, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/10271753---Special-Cat-All-Life-1.5kg-FRONT_1600x1600.jpg?v=1626849784'],
            ['name' => 'SPECIAL CAT Dry Food Chicken and Turkey 1kg', 'category' => 'Cat Food', 'description' => 'SPECIAL CAT all life stages formula with chicken and turkey. Complete balanced nutrition. 1kg pack.', 'price' => 170, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/10271753---Special-Cat-All-Life-1.5kg-FRONT_1600x1600.jpg?v=1626849784'],
            ['name' => 'WHISKAS Cat Dry Food (Adult) Ocean Fish 1kg', 'category' => 'Cat Food', 'description' => 'WHISKAS adult cat food with irresistible ocean fish flavor. Complete daily nutrition. 1kg pack.', 'price' => 184, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10164593_72518af9-93d7-4726-8133-2d16a87491a6_1600x1600.jpg?v=1778553489'],
            ['name' => 'WHISKAS Cat Wet Food Pouch Tuna 80g', 'category' => 'Cat Food', 'description' => 'WHISKAS wet food pouch with tuna flavor. Delicious chunks cats love. 80g pouch.', 'price' => 35, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10178527_74311f03-f135-4262-bc94-38a42216e0c7_800x800.jpg?v=1778553213'],
            ['name' => 'WHISKAS Cat Wet Food in Can Ocean Fish 400g', 'category' => 'Cat Food', 'description' => 'WHISKAS canned wet food with ocean fish. Rich meaty meal for adult cats. 400g can.', 'price' => 115, 'unit' => 'CAN', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10280950_b477d8b7-a83b-4257-97ba-b8529d5351f4_1600x1600.jpg?v=1778552940'],
            ['name' => 'FREYA Premium Cat Food (All Life Stages) 1kg', 'category' => 'Cat Food', 'description' => 'FREYA premium cat food suitable for all life stages. High-quality protein for overall health. 1kg pack.', 'price' => 210, 'unit' => '1kilogram', 'image' => 'https://www.petcultureph.com/cdn/shop/files/FreyaPremiumCatFood1kg1.png?v=1758954290'],
            ['name' => 'TOP CAT Cat Meal (Adult) 1kg', 'category' => 'Cat Food', 'description' => 'TOP CAT affordable adult cat meal. Balanced everyday nutrition. 1kg pack.', 'price' => 120, 'unit' => '1kilogram', 'image' => 'https://whisfurpetsupplies.com/cdn/shop/files/cat-topcat-tuna-adult-1000g_a68dfa7a-eeca-4bc5-a1ee-b4a8fa277d30.jpg?v=1752410630'],
            ['name' => 'ZOI CAT Adult Tuna 1kg', 'category' => 'Cat Food', 'description' => 'ZOI CAT adult formula with tuna. Delicious and nutritious daily cat food. 1kg pack.', 'price' => 130, 'unit' => '1kilogram', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/10282821-Zoi-Tuna-Adult-Dry-Cat-Food-1kg-front_1600x1600.png?v=1745463544'],
            ['name' => 'WILLOW Cat Dry Food Yellowfin Tuna Wild Salmon 1kg', 'category' => 'Cat Food', 'description' => 'WILLOW premium cat food with yellowfin tuna and wild-caught salmon. All life stages. 1kg pack.', 'price' => 176, 'unit' => '1kilogram', 'image' => 'https://willowpetfood.com/wp-content/uploads/2026/03/cat-pet-food.png'],
            ['name' => 'ROYAL CANIN FBN Persian Adult 400g', 'category' => 'Cat Food', 'description' => 'ROYAL CANIN breed-specific nutrition for Persian cats. Supports skin, coat and digestion. 400g pouch.', 'price' => 350, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10164603_24ab824d-d1d9-4535-b712-8a73b336ef3f_1600x1600.jpg?v=1778552509'],
            ['name' => 'ROYAL CANIN FCN Kitten 400g', 'category' => 'Cat Food', 'description' => 'ROYAL CANIN kitten formula supporting immune system and healthy digestion. Premium quality. 400g pouch.', 'price' => 450, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10164602_cfddcb9d-ce38-40de-b59a-34d91bb9de34_1600x1600.jpg?v=1778552483'],
            ['name' => 'PURINA Felix Cat Wet Food Chicken in Jelly 85g', 'category' => 'Cat Food', 'description' => 'PURINA Felix wet food with tender chicken in jelly. Irresistible taste cats crave. 85g pouch.', 'price' => 30, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/10289765-Purina-Felix-Kitten-Tuna-Jelly-cat-pouch-85g-front_1600x1600.png?v=1681371871'],

            // ── Dog Treats (10) ──
            ['name' => 'DENTALIGHT Beefy Licious Wagyu Beef Jerky 70g', 'category' => 'Dog Treats', 'description' => 'DENTALIGHT premium jerky treats with fillet of wagyu beef. High-protein reward for dogs. 70g pack.', 'price' => 150, 'unit' => 'PIECE', 'image' => 'https://blade.ph/cdn/shop/files/ssph.zone-1751867255-DENTALIGHT_DOG_TREATS_BEEFY_LICIOUS_JERKY_FILLET_OF_WAGYU_BEEF__70G_-1_600x.jpg?v=1751867302'],
            ['name' => 'DENTALIGHT Chicken Licious Fillet of Chicken 70g', 'category' => 'Dog Treats', 'description' => 'DENTALIGHT chicken jerky treats. Real chicken fillet for a tasty, healthy snack. 70g pack.', 'price' => 150, 'unit' => 'PIECE', 'image' => 'https://dogsandthecityph.com/cdn/shop/files/13036_ee5e23b1-fada-4425-95d2-2ff10abc45f2.jpg?v=1740797080'],
            ['name' => 'DENTALIGHT NUTRI DINER Dental Dog Treats Beef 90g', 'category' => 'Dog Treats', 'description' => 'DENTALIGHT dental treats that clean teeth while your dog chews. Beef flavor. 90g pack.', 'price' => 150, 'unit' => 'PIECE', 'image' => 'https://www.petcultureph.com/cdn/shop/files/4_5NutriDinerTastyBeefFlavourx2pcs90g_JPG_34a079a2-df3c-48c8-affe-43249315bb9b.png?v=1759130954'],
            ['name' => 'DOGGO Jumbo Hotdog Beef 100g', 'category' => 'Dog Treats', 'description' => 'DOGGO jumbo hotdog treat with real beef. Fun, delicious snack for all life stages. 100g piece.', 'price' => 70, 'unit' => 'PIECE', 'image' => 'https://blade.ph/cdn/shop/files/ssph.zone-1722389847-DOGGO_DOG_TREATS_JUMBO_HOTDOG_BEEF_FLAVOUR__100G_-1.jpg?v=1722393815'],
            ['name' => 'ENTRÉE Dog Treats American Bacon 70g', 'category' => 'Dog Treats', 'description' => 'ENTRÉE gourmet dog treats with smoky American bacon flavor. Premium snack. 70g pouch.', 'price' => 100, 'unit' => 'POUCH', 'image' => 'https://www.petcultureph.com/cdn/shop/files/EntreeGourmetTreatsPrimeAngusSteak_jpg.png?v=1698031554'],
            ['name' => 'ENTRÉE Dog Treats Prime Angus Steak 70g', 'category' => 'Dog Treats', 'description' => 'ENTRÉE premium treats with prime Angus steak flavor. Restaurant-quality snack for dogs. 70g pouch.', 'price' => 100, 'unit' => 'POUCH', 'image' => 'https://www.petcultureph.com/cdn/shop/files/EntreeGourmetTreatsPrimeAngusSteak_jpg.png?v=1698031554'],
            ['name' => 'FURRPALS Beef Biscuit 230g', 'category' => 'Dog Treats', 'description' => 'FURRPALS crunchy beef biscuits. Perfect training treat or everyday snack. 230g pouch.', 'price' => 150, 'unit' => 'POUCH', 'image' => 'https://img.lazcdn.com/g/p/171acc6358189656dae3bd093d7d3854.png_720x720q80.png'],
            ['name' => 'FURRPALS Dental Chew Treats Beef Yogurt 100g', 'category' => 'Dog Treats', 'description' => 'FURRPALS dental chew treats with beef yogurt flavor. Cleans teeth and freshens breath. 100g pouch.', 'price' => 100, 'unit' => 'POUCH', 'image' => 'https://img.lazcdn.com/g/p/80dbb8200c1cdf59b98a804d396c6a21.jpg_720x720q80.jpg_.webp'],
            ['name' => 'PEDIGREE Schmackos Grilled Liver 70g', 'category' => 'Dog Treats', 'description' => 'PEDIGREE Schmackos with grilled liver flavor. Irresistible strip treats dogs love. 70g pouch.', 'price' => 110, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10307662_e73d3f84-ffd9-4787-8724-bd26c71ae1d6_1600x1600.jpg?v=1778556820'],
            ['name' => 'ZERT Dog Dentacare Blueberry Cheesecake 55g', 'category' => 'Dog Treats', 'description' => 'ZERT dental care treats with blueberry cheesecake flavor. Unique dessert-flavored dental chew. 55g pouch.', 'price' => 90, 'unit' => 'POUCH', 'image' => 'https://blade.ph/cdn/shop/products/ssph.zone-1691036764-ZERT_BLUEBERRY_CHEESECAKE_DENTACARE_DENTAL_STICKS_FOR_DOGS_55G_2_1024x.jpg?v=1691037448'],

            // ── Cat Treats (8) ──
            ['name' => 'AOZI Cat Puree Stick 15g', 'category' => 'Cat Treats', 'description' => 'AOZI creamy cat puree stick. Lickable treat cats go crazy for. 15g per piece.', 'price' => 30, 'unit' => 'PIECE', 'image' => 'https://symphonixph.com/wp-content/uploads/2025/10/Aozi-Cat_Puree_Treats_All_Flavors-15g-scaled.jpg'],
            ['name' => 'JACKPOT Cat Treats Creamy Sticks Chicken 14gx5', 'category' => 'Cat Treats', 'description' => 'JACKPOT creamy sticks with chicken flavor. 5 individually wrapped treats per pack. 14g each.', 'price' => 80, 'unit' => 'POUCH', 'image' => 'https://pineapplepets.ph/cdn/shop/files/Jackpot.png?v=1772185597'],
            ['name' => 'JACKPOT Cat Treats Creamy Sticks Salmon 14gx5', 'category' => 'Cat Treats', 'description' => 'JACKPOT creamy sticks with salmon flavor. 5 individually wrapped treats per pack. 14g each.', 'price' => 80, 'unit' => 'POUCH', 'image' => 'https://pineapplepets.ph/cdn/shop/files/Jackpot.png?v=1772185597'],
            ['name' => 'TEMPTATIONS Creamy Purrrr-ee Chicken & Tuna 48g', 'category' => 'Cat Treats', 'description' => 'TEMPTATIONS creamy puree with chicken and tuna combo. Irresistible lickable treat. 48g pouch.', 'price' => 145, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10283794_65c43130-abe3-4cd9-8f47-1e4524cdd8ad_1600x1600.jpg?v=1778556131'],
            ['name' => 'TEMPTATIONS Creamy Purrrr-ee Salmon & Cheese 48g', 'category' => 'Cat Treats', 'description' => 'TEMPTATIONS creamy puree with salmon and cheese. Rich, indulgent cat treat. 48g pouch.', 'price' => 145, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10283794_65c43130-abe3-4cd9-8f47-1e4524cdd8ad_1600x1600.jpg?v=1778556131'],
            ['name' => 'SHEBA Cat Wet Food Chicken Premium Loaf 70g', 'category' => 'Cat Treats', 'description' => 'SHEBA premium chicken loaf wet food. Restaurant-quality meal for discerning cats. 70g pouch.', 'price' => 47, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10211445_a173e918-b673-4a24-b47d-d8cd8c2cf78d_1600x1600.jpg?v=1778555048'],
            ['name' => 'SHEBA Cat Wet Food Tuna and Salmon 70g', 'category' => 'Cat Treats', 'description' => 'SHEBA premium tuna and salmon combination. Gourmet quality seafood treat. 70g pouch.', 'price' => 47, 'unit' => 'POUCH', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10211445_a173e918-b673-4a24-b47d-d8cd8c2cf78d_1600x1600.jpg?v=1778555048'],
            ['name' => 'FURRPALS Catnip Biscuits 160g', 'category' => 'Cat Treats', 'description' => 'FURRPALS catnip-infused biscuits. Fun, stimulating treats cats love. 160g tub.', 'price' => 120, 'unit' => 'TUB', 'image' => 'https://img.lazcdn.com/g/p/a0a5b3a9150e27387d914a4a9b209422.jpg_720x720q80.jpg'],

            // ── Grooming & Hygiene (18) ──
            ['name' => 'SAINT ROCHE Premium Dog Shampoo Happiness 250ml', 'category' => 'Grooming & Hygiene', 'description' => 'SAINT ROCHE premium shampoo with Happiness scent. Gentle formula for a clean, fragrant coat. 250ml bottle.', 'price' => 280, 'unit' => 'BOTTLE', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10215801SaintRochePremiumHappinessScentDogShampoo1000mlA_1600x1600.png?v=1746015766'],
            ['name' => 'SAINT ROCHE Premium Dog Soap Heaven Scent 135g', 'category' => 'Grooming & Hygiene', 'description' => 'SAINT ROCHE premium dog soap with heavenly scent. Moisturizing and deodorizing. 135g bar.', 'price' => 175, 'unit' => 'POUCH', 'image' => 'https://blade.ph/cdn/shop/products/1_fdca5cd3-f02b-4aae-908a-1615b6d07af1_1024x.jpg?v=1662954395'],
            ['name' => 'FURGANICS 4in1 Conditioning Shampoo Classic 250ml', 'category' => 'Grooming & Hygiene', 'description' => 'FURGANICS 4-in-1 shampoo with conditioner. Classic scent. Cleans, conditions, deodorizes, and detangles. 250ml.', 'price' => 120, 'unit' => 'BOTTLE', 'image' => 'https://filebroker-cdn.lazada.com.ph/kf/Sac109c4e1da14c56921adf35e13c85cfV.jpg'],
            ['name' => 'FURGANICS Anti-Tick and Flea Whipped Pet Soap 135g', 'category' => 'Grooming & Hygiene', 'description' => 'FURGANICS anti-tick and flea soap with virgin coconut oil. Natural pest protection. 135g bar.', 'price' => 99, 'unit' => 'POUCH', 'image' => 'https://img.lazcdn.com/g/p/a92b8b79f0e1bdf7cc8d523183aad5fd.jpg_720x720q80.jpg'],
            ['name' => 'FURMAGIC Dog Soap Blue Butter Fresh Scent 108g', 'category' => 'Grooming & Hygiene', 'description' => 'FURMAGIC dog soap with butter fresh scent. Blue variant. Gentle cleansing formula. 108g bar.', 'price' => 150, 'unit' => 'POUCH', 'image' => 'https://blade.ph/cdn/shop/files/ca219dcf46f01a577dee390975c17d5b.jpg?v=1688698882'],
            ['name' => 'MADRE DE CACAO Shampoo with Conditioner 250ml', 'category' => 'Grooming & Hygiene', 'description' => 'MADRE DE CACAO herbal shampoo with conditioner. Natural formula for healthy skin and coat. 250ml bottle.', 'price' => 150, 'unit' => 'BOTTLE', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10315018SafeHouseMadredeCacaoandLavenderPetShampoo250mlA_1600x1600.png?v=1727247924'],
            ['name' => 'MADRE DE CACAO Herb Spray Anti Tick and Fleas 250ml', 'category' => 'Grooming & Hygiene', 'description' => 'MADRE DE CACAO herbal spray for tick and flea prevention. Natural and safe for pets. 250ml bottle.', 'price' => 230, 'unit' => 'BOTTLE', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/IMG_2021_02_18_3821_1600x1600.jpg?v=1616948242'],
            ['name' => 'MADRE DE CACAO Premium Herbal Soap 135g', 'category' => 'Grooming & Hygiene', 'description' => 'MADRE DE CACAO herbal soap for pets. Natural ingredients for healthy skin. 135g bar.', 'price' => 80, 'unit' => 'PIECE', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10315202SafeHouseMadredeCacaoHerbalBarPetShampoo135gA_1600x1600.png?v=1727247905'],
            ['name' => 'MADRE DE CACAO Cologne Sakura Cherry Blossom 100ml', 'category' => 'Grooming & Hygiene', 'description' => 'MADRE DE CACAO pet cologne with sakura cherry blossom scent. Long-lasting freshness. 100ml bottle.', 'price' => 150, 'unit' => 'PIECE', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/IMG_2021_02_18_3821_1600x1600.jpg?v=1616948242'],
            ['name' => 'ROYAL TAIL ESSENTIALS Shampoo Alpine Breeze 200ml', 'category' => 'Grooming & Hygiene', 'description' => 'ROYAL TAIL ESSENTIALS shampoo with refreshing alpine breeze scent. Gentle on skin. 200ml bottle.', 'price' => 100, 'unit' => 'BOTTLE', 'image' => 'https://blade.ph/cdn/shop/files/FRESHPUPPY-5_1024x.jpg?v=1768294594'],
            ['name' => 'PETCORE Dry Shampoo Powder Fresh 380g', 'category' => 'Grooming & Hygiene', 'description' => 'PETCORE waterless dry shampoo powder. Fresh scent. Perfect for quick cleaning without water. 380g tub.', 'price' => 200, 'unit' => 'TUB', 'image' => 'https://img.lazcdn.com/g/p/aad0d266e1b8529b3b055a1f4c683037.jpg_720x720q80.jpg_.webp'],
            ['name' => 'BABY BOO Pet Wipes 80 Leaves', 'category' => 'Grooming & Hygiene', 'description' => 'BABY BOO gentle pet wipes for quick cleaning. Hypoallergenic and alcohol-free. 80 leaves per pack.', 'price' => 100, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/a3154e30a142aa87d0c7070687da5079.png_720x720q80.png_.webp'],
            ['name' => 'BABY BOO Pet Diaper Female M 14pcs', 'category' => 'Grooming & Hygiene', 'description' => 'BABY BOO disposable pet diaper for female dogs. Medium size. Absorbent and leak-proof. 14 pieces.', 'price' => 210, 'unit' => 'PIECE', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10304099-Baby-Boo-Female-Diaper-16s-Small-FRONT_800x800.png?v=1705290468'],
            ['name' => 'BOW WOW Pet Pad Large 60x60cm', 'category' => 'Grooming & Hygiene', 'description' => 'BOW WOW absorbent pet training pad. Large size 60x60cm. Great for potty training and indoor use.', 'price' => 10, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/a63f338551ff22369d751d2b951f570a.jpg_720x720q80.jpg'],
            ['name' => 'CATTITUDE Lovely Lavender Cat Litter 10L', 'category' => 'Grooming & Hygiene', 'description' => 'CATTITUDE clumping cat litter with lovely lavender scent. Superior odor control. 10L sack.', 'price' => 260, 'unit' => 'SACK', 'image' => 'https://img.lazcdn.com/g/p/4c15fce8eb1189db1e7f574cb3889457.png_720x720q80.png_.webp'],
            ['name' => 'CATSAN Clumping Cat Litter Green 5L', 'category' => 'Grooming & Hygiene', 'description' => 'CATSAN clumping cat litter. Green variant with excellent moisture absorption. 5L sack.', 'price' => 190, 'unit' => 'SACK', 'image' => 'https://www.petexpress.com.ph/cdn/shop/files/10224322_f7f7d0fe-91cd-43a6-8e78-e1ebd2ac2159_1600x1600.jpg?v=1778554910'],
            ['name' => 'ZEN CLEAN Cat Litter Lavender 10L', 'category' => 'Grooming & Hygiene', 'description' => 'ZEN CLEAN cat litter with calming lavender scent. Strong clumping and odor control. 10L sack.', 'price' => 235, 'unit' => 'SACK', 'image' => 'https://www.petcultureph.com/cdn/shop/files/LitterBoxyellowgreen.png?v=1744186538'],
            ['name' => 'PurPaws Natural Pet Body Wipes 50 Sheets', 'category' => 'Grooming & Hygiene', 'description' => 'PurPaws natural body wipes for pets. Gentle, plant-based formula. 50 sheets per pack.', 'price' => 75, 'unit' => 'PIECE', 'image' => 'https://petfriendlys.ph/cdn/shop/files/Purpaws_Hypoallergenic_Pet_Cleaning_Body_Pet_Wipes_Pet_Friendly_s_PH_1.png?v=1743670767'],

            // ── Health & Vitamins (9) ──
            ['name' => 'LC-VIT PLUS 120ml', 'category' => 'Health & Vitamins', 'description' => 'LC-VIT PLUS multivitamins for pets. Enhanced formula with L-carnitine for energy and vitality. 120ml box.', 'price' => 145, 'unit' => 'BOX', 'image' => 'https://blade.ph/cdn/shop/products/1_d4be5bd3-7354-4bc1-bc98-fd9e2190d5af.jpg?v=1660025764'],
            ['name' => 'LC-VIT 60ml', 'category' => 'Health & Vitamins', 'description' => 'LC-VIT multivitamin supplement for dogs and cats. Supports overall health. 60ml box.', 'price' => 100, 'unit' => 'BOX', 'image' => 'https://www.petexpress.com.ph/cdn/shop/products/10211829-LC-Vit-Pet-Multivitamins-in-Syrup-120ml-front_1600x1600.png?v=1649819866'],
            ['name' => 'COATSHINE 120ml', 'category' => 'Health & Vitamins', 'description' => 'COATSHINE coat supplement for shiny, healthy fur. Rich in omega fatty acids. 120ml box.', 'price' => 305, 'unit' => 'BOX', 'image' => 'https://blade.ph/cdn/shop/products/1_789b5753-78da-4478-95b9-b7611322855a_1024x.jpg?v=1660019829'],
            ['name' => 'PAPI OB Vitamins Moringa Strawberry 120ml', 'category' => 'Health & Vitamins', 'description' => 'PAPI OB vitamins with minerals and moringa. Strawberry flavor pets love. 120ml bottle.', 'price' => 180, 'unit' => 'BOTTLE', 'image' => 'https://www.petcultureph.com/cdn/shop/files/PapiOB_jpg.png?v=1693801731'],
            ['name' => 'PAPI DOXY Doxycycline 60ml', 'category' => 'Health & Vitamins', 'description' => 'PAPI DOXY antibiotic for pets. Doxycycline formula for bacterial infections. 60ml bottle. Consult vet before use.', 'price' => 250, 'unit' => 'BOTTLE', 'image' => 'https://www.petcultureph.com/cdn/shop/files/PapiDoxySyrup60ml.png?v=1716868850'],
            ['name' => 'ROYAL TAIL ESSENTIALS RoyalVit Multivitamins 120ml', 'category' => 'Health & Vitamins', 'description' => 'ROYAL TAIL ESSENTIALS multivitamin supplement for pets. Supports immune system and overall health. 120ml box.', 'price' => 145, 'unit' => 'BOX', 'image' => 'https://hospetsupplies.com/cdn/shop/files/sg-11134201-7rd3k-lvv9n0id97gsa6.jpg?v=1727250701'],
            ['name' => 'NEXGARD Dogs 4-10kg 28.3mg', 'category' => 'Health & Vitamins', 'description' => 'NEXGARD chewable flea and tick treatment for dogs 4-10kg. Monthly protection. Single tablet.', 'price' => 650, 'unit' => 'Tablet', 'image' => 'https://blade.ph/cdn/shop/products/ssph.zone-1658125081-NEXGARD_SPECTRA_CHEWABLE_TABLET_15-30_KG-4_1024x.jpg?v=1658125233'],
            ['name' => 'PYRANTEL Nematocide 15ml', 'category' => 'Health & Vitamins', 'description' => 'PYRANTEL dewormer for dogs and cats. Effective against roundworms and hookworms. 15ml box.', 'price' => 130, 'unit' => 'BOX', 'image' => 'https://blade.ph/cdn/shop/products/ssph.zone-1651806328-1.jpg?v=1652153254'],
            ['name' => 'FURGANICS Cure All Ointment 10g', 'category' => 'Health & Vitamins', 'description' => 'FURGANICS cure all ointment for skin issues. Treats mange, wounds, and fungal infections. 10g tub.', 'price' => 120, 'unit' => 'TUB', 'image' => 'https://ph-test-11.slatic.net/p/ca44e7ec891c2d8cc27a77a20ded6448.jpg'],

            // ── Accessories (14) ──
            ['name' => 'Pet Stainless Steel Bowl 22cm', 'category' => 'Accessories', 'description' => 'Durable stainless steel pet bowl. 22cm diameter. Non-slip base. Easy to clean. Suitable for dogs and cats.', 'price' => 95, 'unit' => 'PIECE', 'image' => 'https://www.petcultureph.com/cdn/shop/files/1_4330c538-6633-43cc-ae6b-0c0d8691566c.png?v=1695018855'],
            ['name' => 'Pet 2in1 Feeder Bowl with Drinking Bottle', 'category' => 'Accessories', 'description' => 'Convenient 2-in-1 pet feeder with attached water bottle. Food and water in one compact unit.', 'price' => 100, 'unit' => 'PIECE', 'image' => 'https://ph-test-11.slatic.net/p/e6cb9063f46b276735ea6a9761cfeafe.jpg'],
            ['name' => 'Dog Harness with Leash Soft Mesh Breathable Medium', 'category' => 'Accessories', 'description' => 'Soft mesh breathable dog harness with leash included. Medium size. Comfortable for daily walks.', 'price' => 70, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/873bd4e122f93b4f629f34cdf732ee9e.jpg_webp_720x720q80.jpg_.webp'],
            ['name' => 'Dog Leash Large 1.2M Fashion Color', 'category' => 'Accessories', 'description' => 'Stylish 1.2M dog leash in fashion colors. Large size for bigger dogs. Strong and durable.', 'price' => 105, 'unit' => 'PIECE', 'image' => 'https://blade.ph/cdn/shop/products/ssph.zone-1640655858-Untitled-2.jpg?v=1640838686'],
            ['name' => 'Pet Collar Dog Paw with Bell', 'category' => 'Accessories', 'description' => 'Cute pet collar with paw design and bell. Adjustable fit for small to medium pets.', 'price' => 30, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/f2c6ebb1707005b758218557dc17b77c.jpg_720x720q80.jpg'],
            ['name' => 'Pet Carrier Backpack', 'category' => 'Accessories', 'description' => 'Portable pet carrier backpack with ventilation windows. Comfortable for both pet and owner. For small pets.', 'price' => 450, 'unit' => 'PIECE', 'image' => 'https://blade.ph/cdn/shop/files/PetBagBackpacksoftpetcarrierforcats_dogs_blue_-2_1024x.jpg?v=1711333491'],
            ['name' => 'PET DISCOUNT Travel Cage 48x32x30cm', 'category' => 'Accessories', 'description' => 'Sturdy pet travel cage. 48x32x30cm dimensions. Secure latch. Suitable for small to medium pets.', 'price' => 600, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/ff/kf/S345ec3c0132c4e379cc7b0e7b2a45973y.jpg_720x720q80.jpg_.webp'],
            ['name' => 'Cat Litter Box with Scoop Highbase Gray Big', 'category' => 'Accessories', 'description' => 'Large cat litter box with high base to prevent spills. Gray color. Includes free scoop.', 'price' => 350, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/5dd96bbecc2a15ee0102f05ff7f1ea78.png_720x720q80.png_.webp'],
            ['name' => 'Pet Nail Clipper Big', 'category' => 'Accessories', 'description' => 'Professional pet nail clipper. Big size for medium to large dogs. Sharp, safe blade with guard.', 'price' => 100, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/f9fcab71961fe2eda4e5f1ac10847352.jpg_720x720q80.jpg_.webp'],
            ['name' => 'Pet Slow Down Feeder Food Bowl', 'category' => 'Accessories', 'description' => 'Slow feeder bowl to prevent fast eating and bloating. Fun maze design. Non-slip base.', 'price' => 68, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/632f859964e153e55538f808940ea9a6.jpg_720x720q80.jpg'],
            ['name' => 'Dog Potty Trainer Small', 'category' => 'Accessories', 'description' => 'Indoor dog potty trainer. Small size. Holds training pads securely. Easy to clean grid tray.', 'price' => 250, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/632f859964e153e55538f808940ea9a6.jpg_720x720q80.jpg'],
            ['name' => 'Pet Toothbrush Set with Beef Toothpaste', 'category' => 'Accessories', 'description' => 'Pet dental care set including toothbrush and beef-flavored toothpaste. Promotes healthy teeth and gums.', 'price' => 72, 'unit' => 'PIECE', 'image' => 'https://petshop.ph/cdn/shop/products/MICHIKO2PCSTOOTHBRUSHSETBLUE-_2.jpg?v=1612579339'],
            ['name' => 'Muzzle Black #3 5-10kg', 'category' => 'Accessories', 'description' => 'Adjustable black muzzle for dogs 5-10kg. Comfortable fit with breathable design. Size #3.', 'price' => 65, 'unit' => 'PIECE', 'image' => 'https://img.lazcdn.com/g/p/881b3b246d7e2effc49820aaf49b3447.jpg_720x720q80.jpg'],
            ['name' => 'E Collar #2', 'category' => 'Accessories', 'description' => 'Pet recovery E-collar (cone of shame). Size #2. Prevents licking and biting wounds after surgery.', 'price' => 110, 'unit' => 'PIECE', 'image' => 'https://www.petcultureph.com/cdn/shop/files/e-collar2_f8bec878-eb29-4b5f-87be-9600c5a7284d.png?v=1694591603'],

            // ── Toys (6) ──
            ['name' => 'Pet Dog Squeaky Teether Training Chew Toy Ball', 'category' => 'Toys', 'description' => 'Squeaky ball chew toy for dogs. Durable rubber with built-in squeaker. Great for fetch and teething.', 'price' => 40, 'unit' => 'PIECE', 'image' => 'https://blade.ph/cdn/shop/products/ssph.zone-1641170844-Doggo_Squeaky_Ball__Blue_-1.jpg?v=1641171082'],
            ['name' => 'Pet Dog Squeaky Teether Training Chew Toy Bone Big', 'category' => 'Toys', 'description' => 'Large squeaky bone chew toy for dogs. Durable material for aggressive chewers. Built-in squeaker.', 'price' => 80, 'unit' => 'PIECE', 'image' => 'https://blade.ph/cdn/shop/products/ssph.zone-1641295410-Doggo_Squeaky_Rugby__Colors_-1.jpg?v=1641295453'],
            ['name' => 'Pet Dog Toys Sounding Interactive Plush Chew Toy Bone', 'category' => 'Toys', 'description' => 'Soft plush bone toy with sound. Interactive play for puppies and small dogs. Cuddly and fun.', 'price' => 50, 'unit' => 'PIECE', 'image' => 'https://petshop.ph/cdn/shop/products/ssph.zone-1631774253-3.jpg?v=1631774817'],
            ['name' => 'Colorful Rubber Dog Toys Round Woven with Bell', 'category' => 'Toys', 'description' => 'Colorful woven rubber toy with built-in bell. Stimulates play and exercise. Durable braided design.', 'price' => 65, 'unit' => 'PIECE', 'image' => 'https://petshop.ph/cdn/shop/products/ssph.zone-1637197908-Doggo_Rattan_Ball__1.jpg?v=1637198186'],
            ['name' => 'Cat Teaser Bell Feather Toy', 'category' => 'Toys', 'description' => 'Interactive cat teaser wand with bell and feather. Stimulates hunting instincts. Hours of entertainment.', 'price' => 45, 'unit' => 'PIECE', 'image' => 'https://petshop.ph/cdn/shop/products/CATTOYSA16004_3SIMUBEIBEI_3.jpg?v=1611727520'],
            ['name' => 'Mini Cat Grinding Interactive Plush', 'category' => 'Toys', 'description' => 'Mini interactive plush toy for cats. Grinding texture for teeth health. Compact and adorable.', 'price' => 60, 'unit' => 'PIECE', 'image' => 'https://blade.ph/cdn/shop/products/1_d5be30b9-54c5-437d-8f15-f4c88f8e0af7_1024x.jpg?v=1662021353'],
        ];

        foreach ($products as $product) {
            $categoryId = $categories[$product['category']] ?? null;

            if (!$categoryId) {
                $this->command->warn("Category '{$product['category']}' not found, skipping: {$product['name']}");
                continue;
            }

            Product::updateOrCreate(
                ['name' => $product['name']],
                [
                    'category_id'  => $categoryId,
                    'description'  => $product['description'],
                    'price'        => $product['price'],
                    'cost_price'   => round($product['price'] * 0.65, 2),
                    'unit'         => $product['unit'],
                    'stock'        => rand(10, 150),
                    'image_url'    => $product['image'],
                    'is_active'    => true,
                ]
            );
        }

        $this->command->info('Seeded ' . count($products) . ' products successfully!');
    }
}
